# Generated by Django 5.2.7 on 2025-10-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='references/'),
        ),
    ]
