# Generated by Django 5.2.7 on 2025-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_camera_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
