# Generated by Django 5.2.7 on 2025-11-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_camera_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('usb', 'Cámara USB'), ('ip', 'Cámara IP')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
