# Generated by Django 5.2.7 on 2025-11-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_camera_type_alter_camera_is_active_alter_camera_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
